from typing import List


class JSONLogitsProcessor:
    """
    Enforces strict JSON formatting on LLM outputs by applying 
    grammar-based constraints to prediction logits.
    """
    def __init__(self, vocab: dict):
        self.vocab = vocab

    def apply_constraints(self,
                          logits: List[float],
                          current_text: str
                          ) -> List[float]:
        """
        Constrain logits to ensure the next token conforms to valid JSON syntax.
    
        This method implements a state machine to filter the LLM output based on 
        the current generation context, allowing only tokens that maintain 
        the required structural integrity.
    
        Args:
            logits: A list of raw probability scores from the LLM.
            current_text: The string generated by the model so far.
    
        Returns:
            The filtered list of logits with invalid token scores set to -infinity.
        """
        if not current_text.strip():
            return self._mask_for_start(logits)

        # TODO à compléter avec les autres états (de la machine à états)
        
        return logits

    def _mask_for_start(self, logits: List[float]) -> List[float]:
        """
        Apply a mask that only allows tokens starting with an opening brace '{'.

        This prevents the model from starting its response with conversational 
        fillers or thinking tags.

        Args:
            logits: Current logit distribution from the LLM.

        Returns:
            Logits with a massive penalty applied to all non-compliant tokens.
        """
        new_logits = [-1e10] * len(logits)
        for tid, t_content in self.vocab.items():
            if str(t_content).strip().startswith('{'):
                new_logits[tid] = logits[tid]
        return new_logits
