from src.models import FunctionCallResult
import json


class OutputParser:
    """Class which cleans and validate the generator output"""

    def output_parse(
            self,
            json_str: str,
            original_prompt
            ) -> FunctionCallResult:
        """Cleans and check the string generated by the LLM"""

        start = json_str.find('{')
        end = json_str.rfind('}') + 1
        if start != -1 and end != 0:
            json_str = json_str[start:end]

        try:
            data = json.loads(json_str)
            data["prompt"] = original_prompt
            return FunctionCallResult(**data)
        except json.JSONDecodeError as e:
            raise ValueError(f"JSON mal formé : {e}. Texte reçu : {json_str}")
        except Exception as e:
            raise ValueError(
                f"Erreur de parsing JSON : {e}. "
                f"Contenu : {json_str}"
                )
