from src.models import FunctionCallResult
import json

class OutputParser:
    """Class which cleans and validate the generator output"""

    def output_parse(
            self,
            raw_text: str,
            ) -> FunctionCallResult:
        """Cleans and check the string generated by the LLM"""
        try:
            clean_text = raw_text.strip()
            if clean_text.startswith('[') and clean_text.endswith(']'):
                return json.loads(clean_text[0])
            return json.loads(clean_text)
        except Exception:
            return {"error": "Invalid JSON produced", "raw": raw_text}